import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Banner from "../components/Banner";
import Image from "next/image";
import HeroImage from "../public/hero-image.png";
import { fetchCoffeeStores } from "../lib/coffee-stores";
import { useTrackLocation } from "../hooks/useTrackLocation";
import { useContext, useEffect, useState } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import RenderCoffeeShops from "../components/RenderCoffeeShops";
import { CoffeeStoresContext } from "../context";
interface HomeProps {
  stores: any[];
}

const Home: NextPage<HomeProps> = ({ stores }) => {
  const [error, isLoading, getPosition, resetError] = useTrackLocation();
  const { coordinates, dispatch, coffeeStores } =
    useContext(CoffeeStoresContext);

  const handleOnBannerBtnClick = () => {
    getPosition();
  };

  useEffect(() => {
    if (error) {
      toast.error(error);
      resetError();
    }
  }, [error]);

  useEffect(() => {
    (async () => {
      if (coordinates) {
        try {
          const response = await fetch(
            `/api/getCoffeeStoresByLocation?latLong=${40.5929},${-73.9316}&limit=${7}`
          );
          const coffeeShops = await response.json();
          dispatch({ type: "SET_CS", payload: coffeeShops });
        } catch (e) {
          toast.error((e as Error).message);
        }
      }
    })();
  }, [coordinates]);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Coffee Connoisseur App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <ToastContainer />
          <div className={styles["hero-image"]}>
            <Image src={HeroImage} alt={"hero"} width={700} height={350} />
          </div>
          <Banner
            buttonText={isLoading ? "Locating..." : "View stores nearby"}
            handleOnClick={handleOnBannerBtnClick}
          />
          <RenderCoffeeShops
            stores={coffeeStores}
            title="Coffee Stores near me:"
          />
          <RenderCoffeeShops stores={stores} title="Toronto coffee stores" />
        </main>
      </div>
    </>
  );
};

export async function getStaticProps() {
  const stores = await fetchCoffeeStores();

  return {
    props: { stores },
  };
}

export default Home;
